### ISSUE TITLE
Invalid plugin.yml

### ISSUE THREAD

**Issue by Curtis73** [elBukkit/MagicQuests#1]
Sorry to bother you - for some reason this plugin won't load - in my console it says 'invalid plugin.yml'.

**Comment by NathanWolf** [comment]
No worries!

This isn't a plugin, it's a module for the Quests plugin. You put it in plugins/Quests/modules and it provides some Quests/Magic integration.

**Comment by Curtis73** [comment]
Aha - Thank you :)
