### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by Curtis73** [elBukkit/MagicQuests#2]
Sorry to bother you, but I've tried to get the download for this plugin from your Jenkins server, but it appears to be down!
Is there any other way I can get the download?
Thanks in advance!

**Comment by NathanWolf** [comment]
My build/dev/web server died, HD failure. You can get releases from spigotmc as normal.

**Comment by Curtis73** [comment]
Sorry, but I can't seem to find the MagicQuests module on Spigot. Am I not looking properly or isn't it there?

**Comment by NathanWolf** [comment]
It's not on spigot. It hasn't changed in years though, why do you suddenly need it now?

**Comment by NathanWolf** [comment]
(and sorry, didn't notice which project you were commenting on)

**Comment by NathanWolf** [comment]
Released on github.

https://github.com/elBukkit/MagicQuests/releases/tag/1.0

**Comment by Curtis73** [comment]
Thank you!
