### ISSUE TITLE
Release version 1.2

### ISSUE THREAD

**Issue by PikaMug** [elBukkit/MagicQuests#4]
Would you please either update Jenkins (I assume the latest Quests version is missing) or release MagicQuests 1.2 on Github? Thank you!

https://github.com/elBukkit/MagicQuests/releases/

**Comment by NathanWolf** [comment]
Is latest Quests available in Maven somewhere? If Jenkins can’t built it then I can’t build it either so github releases won’t help.

**Comment by PikaMug** [comment]
Unfortunately not (yet). How were they able to build previously? My knowledge of Jenkins is limited.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NathanWolf** [comment]
I think I have Quests in Jenkins ... I’m out of town but I’ll see if I can get it all updated when I’m back.

**Comment by PikaMug** [comment]
Closing as MagicQuests is now building properly on Jenkins (although not sure if you wish to release on Github as well).

Thank you!

**Comment by NathanWolf** [comment]
Oh good idea, I just added a Github release. Thanks!
